# Welcome to APEC 8602: Applied Earth-Economy Modeling!

**Location:** Ruttan Hall B22 (preferred) or online via Zoom (contact me to get link)

**Timing:** Tuesdays and Thursdays, 8:45-10:00am CT, from September 2 to October 16.

**Github repo:** <https://github.com/jandrewjohnson/apec_8602_2025>

**Syllabus:** [syllabus.html](syllabus.html)

**Google drive:** <https://drive.google.com/drive/folders/14tJubCW5hm3T6cMYwTDElNsvxk1rptgS?usp=sharing>

**Video playlist for all lectures:** <https://www.youtube.com/playlist?list=PLir2vw2cQ_Nsn_zNtX050t5Y49YkxcNRt>

## Schedule

This will be updated as we proceed. If there's not a link to a resource yet, it is not finalized yet and might change.

|            |                                                                                                                                     |                                                                                                                                                                                |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
|------------|------------|------------|------------|------------|------------|
| **Date**   | **Title**                                                                                                                           | **Required Reading(s)**                                                                                                                                                        | **Video**                                                                                         | **Slides**                                                                                                                                                                                                                                                | **Assignments**                                                                                                                                    |
| 2025-09-02 | [01 - Big Picture and Syllabus Introduction](lectures/01-big_picture_and_syllabus_introduction.qmd)                                 |                                                                                                                                                                                | [01](https://www.youtube.com/watch?v=rZSMUSTymGw&list=PLir2vw2cQ_Nsn_zNtX050t5Y49YkxcNRt)         | [01](https://docs.google.com/presentation/d/1NrH3Suyex8A12C5qWp3f3Ib14RYll8Fb/edit?usp=sharing&ouid=103231068717031989778&rtpof=true&sd=true)                                                                                                             |                                                                                                                                                    |
| 2025-09-04 | [02 - Introduction to Earth-Economy Modeling](lectures/02-introduction_to_earth_economy_modeling.qmd)                               | [Johnson et al. (2025)](https://doi.org/10.1146/annurev-resource-013024-033043)                                                                                                | [02](https://www.youtube.com/watch?v=GWIo_f_5XfQ&list=PLir2vw2cQ_Nsn_zNtX050t5Y49YkxcNRt&index=2) | [02](https://docs.google.com/presentation/d/1SSEmKUUdwcuprEmDwKgMpmyzEWI7PsTq?rtpof=true&usp=drive_fs)                                                                                                                                                    | [Assignment 01 - Gitting up to Speed](assignments/01-gitting_up_to_speed.qmd). Due 2025-09-09.                                                     |
| 2025-09-09 | [03 - National Sustainability in General Equilibrium](lectures/03-national_sustainability_in_general_equilibrium.qmd)               | [Banerjee et al. (2025)](https://doi.org/10.1016/j.ecoser.2024.101695) also skim the Supplemental Info, [Banerjee et al. (2020)](https://doi.org/10.1016/j.ecoser.2020.101202) | [03](https://www.youtube.com/watch?v=8arFLjNf9_g&list=PLir2vw2cQ_Nsn_zNtX050t5Y49YkxcNRt&index=3) | [03](https://docs.google.com/presentation/d/1bn52m-L8MBG1OOsLOfUmqRJHiXmNqG98?rtpof=true&usp=drive_fs)                                                                                                                                                    | [Assignment 02 - Geographic Information Systems (GIS) in 1 hour](assignments/02-geographic_information_systems_gis_in_1_hour.qmd). Due 2025-09-16. |
| 2025-09-11 | [04 - Scenarios for the Future and Land-use Change Modeling](lectures/04-scenarios_for_the_future_and_land_use_change_modeling.qmd) | [Hurtt et al. (2020)](https://doi.org/10.5194/gmd-13-5425-2020) and [Popp et al. (2017)](https://doi.org/10.1016/j.gloenvcha.2016.10.002)                                      | [04](https://www.youtube.com/watch?v=kAWmf3hhzuk&list=PLir2vw2cQ_Nsn_zNtX050t5Y49YkxcNRt&index=4) | [04](https://docs.google.com/presentation/d/1HXXMc3kbTawLs3yN6cVlgO8wg_dLg40u?rtpof=true&usp=drive_fs)                                                                                                                                                    |                                                                                                                                                    |
| 2025-09-16 | [05 - Hands on with Climate IAMs](lectures/05-hands_on_with_climate_iams.qmd)                                                       | [Nordhaus 2017](https://doi.org/10.1073/pnas.1609244114), [Moore et al. 2022](https://doi.org/10.1038/s41586-022-04423-8)                                                      | [05](https://www.youtube.com/watch?v=gximiPvGJt4&list=PLir2vw2cQ_Nsn_zNtX050t5Y49YkxcNRt&index=5) | [05prep](https://docs.google.com/presentation/d/1wcfKV7ruNNe8QSFfB2HczaR_o9WSHNIS?rtpof=true&usp=drive_fs), [05](https://docs.google.com/presentation/d/1SzRvkDDaGv1zvN5AkofI4yotLNPQZzIr/edit?usp=sharing&ouid=103231068717031989778&rtpof=true&sd=true) |                                                                                                                                                    |
| 2025-09-18 | Inclusive Wealth, Changing Wealth of Nations, Ecosystem Services                                                                    | [Polasky et al. (2015](https://doi.org/10.1146/annurev-environ-101813-013253))                                                                                                 |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-09-23 | Hands on with Ecosystem services - Part 1                                                                                           | Polasky and Segerson (2009)                                                                                                                                                    |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-09-25 | Hands on with Ecosystem services - Part 2                                                                                           | Chaplin-Kramer et al. (2019)                                                                                                                                                   |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-09-30 | Hands on with Computable General Equilibrium - Part 1                                                                               | Shoven and Whalley (1984)                                                                                                                                                      |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-10-02 | Hands on with Computable General Equilibrium - Part 2                                                                               | Corong et al. (2017)                                                                                                                                                           |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-10-06 | Linking models of land-use change modeling, ecosystem services and macroeconomy                                                     | Verburg and Overmars (2009)                                                                                                                                                    |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-10-08 | GTAP-InVEST                                                                                                                         | Johnson et al. (2023)                                                                                                                                                          |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-10-14 | Topics within CGEs, Gridded Economic Analysis, National scale, R&D                                                                  | Baldos et al. (2019), Baldos et al. (2020)                                                                                                                                     |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |
| 2025-10-16 | Season Finale and Student Presentations                                                                                             |                                                                                                                                                                                |                                                                                                   |                                                                                                                                                                                                                                                           |                                                                                                                                                    |